In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
os.chdir('/content/drive/MyDrive/NLP/Translation')
!ls

'arabic dataset'      get-pip.py.1		  'Translation v2.ipynb'
'chinese dataset'    'italian dataset'		  'Translation v3.ipynb'
 Datasets.ipynb       mbert_confusion_matrix.png  'Translation v4.ipynb'
'Datasets v2.ipynb'   mbert_final		  'Translation v5.ipynb'
 final_models	      merged_datasets		   xlmr_best_model
'french dataset'      sentiment_gpt3_train.jsonl   xlmr_confusion_matrix.png
 get-pip.py	     'Translation v1.ipynb'

In [3]:
import pandas as pd

df = pd.read_csv("merged_datasets/merged_all_languages_clean.csv")

print("Shape:", df.shape)
df.head()

Shape: (427366, 3)

                                                text sentiment language
0  un ème tome incroyable que de rebondissements ...       POS       fr
1                        漏水要退货或者换货 水杯漏水要退货或者换货请尽快联系我       NEG       zh
2       不错的意面 买了两把味道不错 这款意面煮时间长点后相比较要软一点比较适合本人和孩子的口味       POS       zh
3  plutôt pour jouer jai acheté ce micro pour ani...   NEUTRAL       fr
4  nick mason pink floyd complète une collection ...       POS       fr

In [4]:
samples = df.groupby("language").sample(n=1, random_state=42)

samples = samples.reset_index(drop=True)
samples

                                                text sentiment language
0  أذا أقنعت شابا بالكذب بانه يجاهد في سبيل الله ...       NEG       ar
1  pas loin du sac parfait acheté pour une utilis...       POS       fr
2             davvero molto interessante questa cosa       POS       it
3               我能说真的看不下去么 看了不到页好啰嗦呀语言是翻译的原因吧真心感觉不流畅       NEG       zh

In [5]:
df_google = pd.read_csv("merged_datasets/merged_balanced_translated_google_clean.csv")
df_libre = pd.read_csv("merged_datasets/merged_balanced_translated_libre_fixed.csv")

print("Google:", df_google.shape)
print("Libre:", df_libre.shape)

df_google.head()

Google: (11997, 4)
Libre: (12000, 4)

,text,sentiment,language,translated_text
0,بطلنا نحكم على الناس من شكلهم و لبسهم و تمن خر...,NEG,ar,"We stopped judging people by their looks, thei..."
1,vérifier la quantité à la livraison jai acheté...,NEG,fr,check the quantity on delivery I bought these ...
2,برومو حلقة بائع الليمون ثاني حلقات الأنيميشن م...,NEG,ar,"Promo for the Lemon Seller episode, the second..."
3,il governo fino ad ora non avrà proprio spacca...,POS,it,up to now the government hasn't exactly split ...
4,أثار تخريب كنيسة مارجرجس وحرق بيوت الأقباط بقر...,NEG,ar,The vandalism of St. George's Church and the b...

In [8]:
df_google = pd.read_csv("merged_datasets/merged_balanced_translated_google_clean.csv")
df_libre = pd.read_csv("merged_datasets/merged_balanced_translated_libre_fixed.csv")

samples = df_google.groupby("language").sample(n=1, random_state=42).reset_index(drop=True)

samples

,text,sentiment,language,translated_text
0,هل يزول الظلـــم طــوعــا أو حنــانــا للضعـــ...,NEUTRAL,ar,Will injustice go away voluntarily or out of c...
1,machine a fer je suis du tout pas satisfaite d...,NEG,fr,iron machine I am not at all satisfied with th...
2,io a chiederei una cosa sola ma i vestiti li l...,NEG,it,I would only ask one thing but you still wash ...
3,可以用 和原装的差不多质感颜色稍差一点使用感觉还可以,POS,zh,It can be used. The texture is almost the same...

In [9]:
samples = samples.merge(
    df_libre[["text", "translated_text"]],
    on="text",
    how="left"
)

samples = samples.rename(columns={
    "translated_text_x": "google_translation",
    "translated_text_y": "libre_translation"
})

samples

,text,sentiment,language,google_translation,libre_translation
0,هل يزول الظلـــم طــوعــا أو حنــانــا للضعـــ...,NEUTRAL,ar,Will injustice go away voluntarily or out of c...,Does the darkness go away to the weak or to th...
1,machine a fer je suis du tout pas satisfaite d...,NEG,fr,iron machine I am not at all satisfied with th...,iron machine i am at all not satisfied with th...
2,io a chiederei una cosa sola ma i vestiti li l...,NEG,it,I would only ask one thing but you still wash ...,i would ask one thing but the clothes still wa...
3,可以用 和原装的差不多质感颜色稍差一点使用感觉还可以,POS,zh,It can be used. The texture is almost the same...,It's a little bit less of a sense than the ori...